name: CI - Build, Lint, Docs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build clang-tidy doxygen graphviz

      - name: Configure project with CMake
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build project
        run: |
          cmake --build build

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Upload Doxygen HTML as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/html

  deploy-docs:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
